"""Initial migration

Revision ID: 27d1d595ca74
Revises: 
Create Date: 2025-12-20 09:25:35.741179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27d1d595ca74'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('horses',
    sa.Column('horse_id', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('sex', sa.String(length=5), nullable=False),
    sa.Column('birth_year', sa.Integer(), nullable=False),
    sa.Column('father', sa.String(length=50), nullable=True),
    sa.Column('mother', sa.String(length=50), nullable=True),
    sa.Column('mother_father', sa.String(length=50), nullable=True),
    sa.Column('trainer', sa.String(length=50), nullable=True),
    sa.Column('owner', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('horse_id')
    )
    op.create_table('jockeys',
    sa.Column('jockey_id', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('win_rate', sa.Float(), nullable=True),
    sa.Column('place_rate', sa.Float(), nullable=True),
    sa.Column('show_rate', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('jockey_id')
    )
    op.create_table('races',
    sa.Column('race_id', sa.String(length=20), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('course', sa.String(length=10), nullable=False),
    sa.Column('race_number', sa.Integer(), nullable=False),
    sa.Column('race_name', sa.String(length=100), nullable=True),
    sa.Column('distance', sa.Integer(), nullable=False),
    sa.Column('track_type', sa.String(length=10), nullable=False),
    sa.Column('weather', sa.String(length=10), nullable=True),
    sa.Column('condition', sa.String(length=10), nullable=True),
    sa.Column('grade', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('race_id')
    )
    op.create_index(op.f('ix_races_date'), 'races', ['date'], unique=False)
    op.create_table('entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('race_id', sa.String(length=20), nullable=False),
    sa.Column('horse_id', sa.String(length=20), nullable=False),
    sa.Column('jockey_id', sa.String(length=20), nullable=True),
    sa.Column('frame_number', sa.Integer(), nullable=True),
    sa.Column('horse_number', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('horse_weight', sa.Integer(), nullable=True),
    sa.Column('weight_diff', sa.Integer(), nullable=True),
    sa.Column('odds', sa.Float(), nullable=True),
    sa.Column('popularity', sa.Integer(), nullable=True),
    sa.Column('result', sa.Integer(), nullable=True),
    sa.Column('finish_time', sa.String(length=10), nullable=True),
    sa.Column('margin', sa.String(length=20), nullable=True),
    sa.Column('corner_position', sa.String(length=20), nullable=True),
    sa.Column('last_3f', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['horse_id'], ['horses.horse_id'], ),
    sa.ForeignKeyConstraint(['jockey_id'], ['jockeys.jockey_id'], ),
    sa.ForeignKeyConstraint(['race_id'], ['races.race_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entries_horse_id'), 'entries', ['horse_id'], unique=False)
    op.create_index(op.f('ix_entries_race_id'), 'entries', ['race_id'], unique=False)
    op.create_table('predictions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('race_id', sa.String(length=20), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('results_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['race_id'], ['races.race_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_predictions_created_at'), 'predictions', ['created_at'], unique=False)
    op.create_index(op.f('ix_predictions_race_id'), 'predictions', ['race_id'], unique=False)
    op.create_table('history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('prediction_id', sa.Integer(), nullable=False),
    sa.Column('bet_type', sa.String(length=20), nullable=False),
    sa.Column('bet_detail', sa.String(length=50), nullable=False),
    sa.Column('bet_amount', sa.Integer(), nullable=True),
    sa.Column('is_hit', sa.Boolean(), nullable=True),
    sa.Column('payout', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['prediction_id'], ['predictions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('history')
    op.drop_index(op.f('ix_predictions_race_id'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_created_at'), table_name='predictions')
    op.drop_table('predictions')
    op.drop_index(op.f('ix_entries_race_id'), table_name='entries')
    op.drop_index(op.f('ix_entries_horse_id'), table_name='entries')
    op.drop_table('entries')
    op.drop_index(op.f('ix_races_date'), table_name='races')
    op.drop_table('races')
    op.drop_table('jockeys')
    op.drop_table('horses')
    # ### end Alembic commands ###
