from app.schemas.race import (
    HorseBase,
    HorseResponse,
    JockeyBase,
    JockeyResponse,
    EntryBase,
    EntryResponse,
    RaceBase,
    RaceListItem,
    RaceDetail,
    RaceListResponse,
    ScrapeRaceRequest,
    ScrapeRaceResponse,
    ScrapeDetailResponse,
)
from app.schemas.prediction import (
    PredictionItem,
    RecommendedBet,
    PredictionResult,
    PredictionResponse,
    CreatePredictionRequest,
    HistoryBase,
    CreateHistoryRequest,
    HistoryItem,
    HistoryWithRace,
    HistorySummary,
    HistoryListResponse,
    UpdateHistoryResultRequest,
    HistoryUpdateResponse,
    AccuracyStats,
    AccuracyByCategory,
    StatsResponse,
)

__all__ = [
    # Race schemas
    "HorseBase",
    "HorseResponse",
    "JockeyBase",
    "JockeyResponse",
    "EntryBase",
    "EntryResponse",
    "RaceBase",
    "RaceListItem",
    "RaceDetail",
    "RaceListResponse",
    "ScrapeRaceRequest",
    "ScrapeRaceResponse",
    "ScrapeDetailResponse",
    # Prediction schemas
    "PredictionItem",
    "RecommendedBet",
    "PredictionResult",
    "PredictionResponse",
    "CreatePredictionRequest",
    "HistoryBase",
    "CreateHistoryRequest",
    "HistoryItem",
    "HistoryWithRace",
    "HistorySummary",
    "HistoryListResponse",
    "UpdateHistoryResultRequest",
    "HistoryUpdateResponse",
    "AccuracyStats",
    "AccuracyByCategory",
    "StatsResponse",
]
